spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/userservice
    username: userservice
    password: "{cipher}0e470ff00c8e1e95eab715cbc3942d7f534565df0af40433d925809e3c90db158921ecfd081571707ecab250dea6f912"

app:
  token:
    access:
      expiration-hour: 2 # a hour
      secret: hBeI4FVNWKiTOnc06oXg6hMhBoD/No9N2+yHr8JQI5Yav3whOmGVLy7F4R4ZFUlS1lsprYT+PZCZ821S9LI5DA==
    refresh:
      expiration-hour: 24 # a day
      secret: ckoQEuWYg3fjSDsb30HPDK9xcTFogHpHkpgj7EBofs+/Ig5Y3CZ6I9gEKK1wcacDolQtukXFcAFJulWvRvCLdA==
